# Generated by Django 4.1.2 on 2022-10-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestab',
            name='vehicle_type',
            field=models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Two Wheeler', 'Three Wheeler'), ('Two Wheeler', 'Four Wheeler')], max_length=100),
        ),
    ]
