# Generated by Django 4.1.2 on 2022-10-21 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanger', '0002_alter_vehiclestab_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestab',
            name='vehicle_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed')]),
        ),
    ]
